blank_issues_enabled: false
contact_links:
  - name: 'â“ GitHub Discussions Q&A'
    url: 'https://github.com/Viren070/AIOStreams/discussions/categories/help'
    about: 'Ask and answer questions here.'
  - name: 'ğŸ’¬ Join our Discord Community'
    url: 'https://discord.viren070.me'
    about: 'For live discussions and community support, join our Discord server.'
